# Generated by Django 3.2.6 on 2021-08-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_auto_20210814_1929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_subscription',
        ),
    ]
