# Generated by Django 3.2.7 on 2021-10-02 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0009_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
