# Generated by Django 3.2.7 on 2021-10-08 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0011_auto_20211002_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
